//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMI.API.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMMIDemoData : DbContext
    {
        public CMMIDemoData()
            : base("name=CMMIDemoData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuisine> Cuisines { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ViewRestaurant> ViewRestaurants { get; set; }
        public virtual DbSet<ViewReview> ViewReviews { get; set; }
        public virtual DbSet<SysError> SysErrors { get; set; }
        public virtual DbSet<SysTrace> SysTraces { get; set; }
    }
}
