//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMI.API.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReview
    {
        public int Id { get; set; }
        public string Restaurant { get; set; }
        public string Username { get; set; }
        public string Review { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
